package ai.documentationfirst.ddd.actions

import ai.documentationfirst.ddd.notifications.DddNotifications
import com.intellij.icons.AllIcons
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.vfs.LocalFileSystem
import java.io.File
import java.time.LocalDate

/**
 * DDD: Export Copilot Chat
 *
 * Generates a Markdown guide file in `.ai_context/docs/` to help
 * the user export/save their Copilot chat session.
 *
 * ⚠️ The Copilot database (Nitrite/MVStore) is locked while IntelliJ is open.
 *    Direct export is not possible — this guide provides alternatives.
 */
class ExportCopilotChatAction : AnAction(AllIcons.Actions.Download) {

    override fun getActionUpdateThread() = ActionUpdateThread.BGT

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val root = project.basePath ?: return

        val sessionTitle = askInput(
            project,
            "Session title (for file name)",
            "e.g. DDD-session, migration-angular-21"
        ) ?: return

        val outputDir = File(root, ".ai_context/docs").also { it.mkdirs() }
        val today = LocalDate.now().toString()
        val safeTitle = sessionTitle.replace(Regex("[^a-zA-Z0-9_-]"), "-").lowercase()
        val outputFile = File(outputDir, "${today}_${safeTitle}.md")

        outputFile.writeText(generateGuide(sessionTitle, today))

        LocalFileSystem.getInstance().refreshAndFindFileByIoFile(outputDir)?.refresh(true, true)
        openFile(project, outputFile)

        DddNotifications.showInfo(
            project,
            "Export Guide Created ✅",
            "See <code>${outputFile.name}</code> in <code>.ai_context/docs/</code>"
        )
    }

    private fun generateGuide(title: String, date: String): String = """
        # Copilot Chat Export — $title

        *Date: $date*

        ---

        ## ✅ Option 1 — Ask Copilot for a summary (recommended)

        Before closing the IDE or switching sessions:

        1. **In the current Copilot chat**, send this prompt :

        ```
        Summarize this work session in structured Markdown:
        - Session objective
        - Decisions made
        - Files modified (with description of the change)
        - Open points or items for the next session
        ```

        2. **Copy Copilot's response**
        3. **Paste into this file** under the `## Transcript` section below
        4. Open a **new Copilot chat session** (✏️ icon in the panel)

        ---

        ## ✅ Option 2 — Use "Copilot Chat Exporter"

        A dedicated JetBrains plugin for exporting Copilot conversations:

        **Settings → Plugins → Marketplace → search "Copilot Chat Exporter"**

        > ⚠️ This plugin requires the IDE to be **restarted** after closing the project
        > so that the Nitrite/MVStore database is unlocked and readable.

        ---

        ## 📝 Transcript

        > *(Paste here the summary generated by Copilot)*

        ---

        ## 🔗 Useful links

        - Copilot Chat Exporter: https://plugins.jetbrains.com (search "Copilot Chat Exporter")
        - DDD — Documentation First: https://documentationfirst.ai
    """.trimIndent()

    override fun update(e: AnActionEvent) {
        e.presentation.isEnabledAndVisible = e.project != null
    }
}
